set APPVEYOR_BUILD_NUMBER=100
set APPVEYOR_BUILD_VERSION=1.0.0.100
set UMBRACO_PACKAGE_MIN_VERSION=7.1.3
set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=
REM ** Generally branch should be either master or Release **
set APPVEYOR_REPO_BRANCH=master
build.bat